nvchecker: update URL for HWiNFO
Maybe they have been purposely blocking requests from GitHub servers on
that endpoint? Because on my local machine it still works just fine...

Github Actions:

$ nvchecker -c source.toml -e HWiNFO
[E 02-20 22:32:09.189 core:342] HWiNFO: unexpected error happened error=HTTPError(403, 'Forbidden', HTTPResponse(_body=None,_error_is_response_code=True,buffer=<_io.BytesIO object at 0x7f4e541d8540>,code=403,effective_url='https://www.hwinfo.com/news.xml/',error=HTTP 403: Forbidden,headers=<tornado.httputil.HTTPHeaders object at 0x7f4e541d9e20>,reason='Forbidden',request=<tornado.httpclient.HTTPRequest object at 0x7f4e542230d0>,request_time=0.0753173828125,start_time=1708468329.1140199,time_info={'queue': 3.337860107421875e-06, 'namelookup': 0.036846, 'connect': 0.042041, 'appconnect': 0.057634, 'pretransfer': 0.057684, 'starttransfer': 0.07207, 'total': 0.072569, 'redirect': 0.0}))
    Traceback (most recent call last):
      File "/home/runner/.local/lib/python3.8/site-packages/nvchecker/util.py", line 298, in run_one
        version = await self.func(
      File "/home/runner/.local/lib/python3.8/site-packages/nvchecker_source/regex.py", line 22, in get_version
        body = await cache.get(key, get_url)
      File "/home/runner/.local/lib/python3.8/site-packages/nvchecker/util.py", line 237, in get
        r = await fu
      File "/home/runner/.local/lib/python3.8/site-packages/nvchecker_source/regex.py", line 33, in get_url
        res = await session.get(url)
      File "/home/runner/.local/lib/python3.8/site-packages/nvchecker/httpclient/base.py", line 49, in get
        return await self.request(
      File "/home/runner/.local/lib/python3.8/site-packages/nvchecker/httpclient/base.py", line 79, in request
        return await self.request_impl(
      File "/home/runner/.local/lib/python3.8/site-packages/nvchecker/httpclient/tornado_httpclient.py", line 91, in request_impl
        raise err_cls(
    nvchecker.httpclient.base.HTTPError: (403, 'Forbidden', HTTPResponse(_body=None,_error_is_response_code=True,buffer=<_io.BytesIO object at 0x7f4e541d8540>,code=403,effective_url='https://www.hwinfo.com/news.xml/',error=HTTP 403: Forbidden,headers=<tornado.httputil.HTTPHeaders object at 0x7f4e541d9e20>,reason='Forbidden',request=<tornado.httpclient.HTTPRequest object at 0x7f4e542230d0>,request_time=0.0753173828125,start_time=1708468329.1140199,time_info={'queue': 3.337860107421875e-06, 'namelookup': 0.036846, 'connect': 0.042041, 'appconnect': 0.057634, 'pretransfer': 0.057684, 'starttransfer': 0.07207, 'total': 0.072569, 'redirect': 0.0}))